[package]
name = "sleep-audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portaudio = "0.7"
anyhow = "1.0"
rand = "0.8"
rand_distr = "0.4"
